---
development:
  dialect: mysql
  database: didit_development
  user: didit
  password: didit
  host: localhost
  port: 8306
  pool: 5
  options:
    encoding: "utf8_general_ci"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://didit:didit@localhost:8306/didit_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://didit:didit@localhost:8306/didit_production?sslmode=disable"}}
