---
development:
  dialect: mysql
  database: didit_development
  user: didit
  password: didit
  host: localhost
  port: 8306
  pool: 5

test:
  dialect: mysql
  database: didit_test
  user: didit
  password: didit
  host: localhost
  port: 8306
  pool: 5

production:
  dialect: mysql
  database: didit_production
  user: didit
  password: didit
  host: localhost
  port: 8306
  pool: 5
